
describe('Register', function() {
  it('Valid registration', function() {
    cy.server()
    
    cy.visit('https://msdev-very-qqlvosoq.lsdg.com/account/register.page')
    cy.get('select#homeAddress_prefix')
      .select('Mr')
    cy.get('input#firstName.textInput')
      .type('Testbot').should('have.value', 'Testbot')
    cy.get('input#lastName.textInput.lastInSection.short')
      .type('Atron').should('have.value', 'Atron')
    cy.get('select#dateOfBirthDay')
      .select('01')
    cy.get('select#dateOfBirthMonth')
      .select('01')    
    cy.get('select#dateOfBirthYear')
      .select('2001')
    cy.get('input#homeAddress_phoneNumber.textInput.numericOnly')
      .type('07777777777')
    cy.get('input#email.textInput')
      .type('fake@fakebotverycouk.com')
    cy.get('input#secPassword.textInput.password')
      .type('Password01')
    cy.get('input#houseNum.textInput')
      .type('1')
    cy.get('input#postcode.textInput')
      .type('BA13HN')
    cy.get("input#findAddressButton.secondaryButton")
      .click()
    cy.get("input#findAddressButton.secondaryButton")
      .click()
    cy.get("input#findAddressButton.secondaryButton")
      .click()
    cy.get("input#address2.textInput")
      .type("Automation Street")
    cy.get("input#city.textInput")
      .type("Automationville")
    cy.get("input#registerContinueButton.primaryButton").click()
    cy.get("div.message.messageIcon.messageSuccess.message-very").should("exist")
  })
})